puts 'The King'
print 'Yaswanth'
puts ' is a LOVER Boy'

puts '        Y'
puts '       A  A'
puts '      S    C'
puts '     W      A'
puts '    A        N'
puts '   N          T'
puts '  T            A'
puts ' H'


puts 'yashyash          yashyash            yashyashyash               yashyashyashyashyash    yash               yash'
puts ' yashyash        yashyash            yashyashyayash              yashyashyashyashyash    yash               yash'
puts '  yashyash      yashyash            yash        yash             yash                    yash               yash'
puts '   yashyash    yashyash            yash          yash            yash                    yash               yash'
puts '    yashyash  yashyash            yash            yash           yash                    yash               yash'
puts '     yashyashyashyash            yash              yash          yashyashyashyashyash    yashyashyashyashyasyash'  
puts '         yashyash               yashyashyashyashyashyash         yashyashyashyashyash    yashyashyashyashyasyash'
puts '         yashyash              yashyashyashyashyashyayash                        yash    yash               yash'
puts '         yashyash             yash                    yash                       yash    yash               yash'
puts '         yashyash            yash                      yash                      yash    yash               yash'
puts '         yashyash           yash                        yash      yashyashyashyasyash    yash               yash'
puts '         yashyash          yash                          yash     yashyashyashyasyash    yash               yash'